import type { PrismaService } from '../prisma/prisma.service';
import { NotFoundException } from '@nestjs/common';

/**
 * Resolves a league identifier (which may be a slug or a CUID) to the actual league CUID.
 * This is a safety net for when slugs leak through to service methods.
 *
 * @param prisma - PrismaService instance
 * @param leagueIdOrSlug - A league id (CUID) or slug string
 * @returns The resolved league CUID
 */
export async function resolveLeagueId(
  prisma: PrismaService,
  leagueIdOrSlug: string,
): Promise<string> {
  // CUIDs generated by Prisma start with 'c' and are 25 characters
  // If it matches that pattern, it's almost certainly already a real id
  if (/^c[a-z0-9]{24}$/.test(leagueIdOrSlug)) {
    return leagueIdOrSlug;
  }

  // Otherwise, treat it as a slug and resolve to the real id
  const league = await prisma.league.findUnique({
    where: { slug: leagueIdOrSlug },
    select: { id: true },
  });

  if (!league) {
    throw new NotFoundException(
      `League not found: ${leagueIdOrSlug}`,
    );
  }

  return league.id;
}
